// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (c) 2020–2026 Michal Dengusiak & Jakub Ziolkowski and contributors
// Generated by Michal Dengusiak and CodeClaude

using Grasshopper.Kernel;
using SAM.Analytical.Grasshopper.Tas.Properties;
using SAM.Analytical.Tas.TM59;
using SAM.Core;
using SAM.Core.Grasshopper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Nodes;

namespace SAM.Analytical.Grasshopper.Tas
{
    /// <summary>
    /// <b>Diagnostic-only.</b> Taps wires already present on the Part O validation canvas - the design model
    /// feeding <c>Tas.TSDQueryTM59Results._analyticalModel</c>, its <c>spaces</c>/results/successful outputs,
    /// and <c>SAMAnalytical.PreparePartOIteration</c>'s scenarios/notes/refusals - rebuilds the identity and
    /// scenario association maps itself (composing <c>PartODiagnosticLog</c>, which composes
    /// <c>SimulationSpaceMap</c>/<c>OverheatingScenarioMap</c>), and writes one JSON Lines summary file plus an
    /// optional hourly companion beside the TAS outputs.
    /// <para>
    /// <b>Runs no simulation and mutates no model.</b> It does not call <c>WorkflowCalculator</c>, does not open
    /// a TBD/TSD/T3D document, and returns nothing that feeds back into a compliance path - only file paths and
    /// counts. Connecting or disconnecting this component from the canvas cannot change a TM59 pass/fail.
    /// </para>
    /// </summary>
    public class TasLogPartODiagnostics : GH_SAMVariableOutputParameterComponent
    {
        /// <summary>
        /// Gets the unique ID for this component. Do not change this ID after release.
        /// </summary>
        public override Guid ComponentGuid => new Guid("fb234a4c-4302-4490-b6a7-6b19f9495fbc");

        /// <summary>
        /// The latest version of this component
        /// </summary>
        public override string LatestComponentVersion => "1.0.0";

        public override GH_Exposure Exposure => GH_Exposure.quarternary;

        /// <summary>
        /// Provides an Icon for the component.
        /// </summary>
        protected override System.Drawing.Bitmap Icon => Resources.SAM_TasTSD3;

        /// <summary>
        /// Initializes a new instance of the TasLogPartODiagnostics class.
        /// </summary>
        public TasLogPartODiagnostics()
          : base("Tas.LogPartODiagnostics", "Tas.LogPartODiagnostics",
              "Writes a diagnostic JSON Lines log of a Part O run - identity, Part F rates, scenarios and TM59 results - beside the TAS outputs. Diagnostic-only: runs no simulation, changes no compliance answer.",
              "SAM", "Tas")
        {
        }

        /// <summary>
        /// Registers all the input parameters for this component.
        /// </summary>
        protected override GH_SAMParam[] Inputs
        {
            get
            {
                List<GH_SAMParam> result = [];

                result.Add(new GH_SAMParam(new GooAnalyticalModelParam() { Name = "_analyticalModel", NickName = "_analyticalModel", Description = "SAM Analytical Model - the same wire as Tas.TSDQueryTM59Results._analyticalModel. Carries PartFSpaceData and the Part-F-applied InternalCondition, both of which survive WorkflowCalculator.Calculate unchanged.", Access = GH_ParamAccess.item }, ParamVisibility.Binding));
                result.Add(new GH_SAMParam(new global::Grasshopper.Kernel.Parameters.Param_String() { Name = "_pathTasTSD", NickName = "_pathTasTSD", Description = "The same wire as Tas.TSDQueryTM59Results._pathTasTSD. Used only to place the log beside the TAS outputs and name it after them - never opened.", Access = GH_ParamAccess.item }, ParamVisibility.Binding));
                result.Add(new GH_SAMParam(new GooSpaceParam() { Name = "spaces_", NickName = "spaces_", Description = "The simulated spaces - Tas.TSDQueryTM59Results.spaces.", Access = GH_ParamAccess.list, Optional = true }, ParamVisibility.Binding));
                result.Add(new GH_SAMParam(new GooAnalyticalObjectParam() { Name = "overheatingScenarios_", NickName = "overheatingScenarios_", Description = "SAM Part O Overheating Scenarios - SAMAnalytical.PreparePartOIteration.overheatingScenarios.", Access = GH_ParamAccess.list, Optional = true }, ParamVisibility.Binding));
                result.Add(new GH_SAMParam(new global::Grasshopper.Kernel.Parameters.Param_String() { Name = "notes_", NickName = "notes_", Description = "SAMAnalytical.PreparePartOIteration.notes.", Access = GH_ParamAccess.list, Optional = true }, ParamVisibility.Binding));
                result.Add(new GH_SAMParam(new global::Grasshopper.Kernel.Parameters.Param_String() { Name = "refusals_", NickName = "refusals_", Description = "SAMAnalytical.PreparePartOIteration.refusals.", Access = GH_ParamAccess.list, Optional = true }, ParamVisibility.Binding));
                result.Add(new GH_SAMParam(new GooResultParam() { Name = "tM59MechanicalVentilationResults_", NickName = "tM59MechanicalVentilationResults_", Description = "Tas.TSDQueryTM59Results.tM59MechanicalVentilationResults.", Access = GH_ParamAccess.list, Optional = true }, ParamVisibility.Binding));
                result.Add(new GH_SAMParam(new GooResultParam() { Name = "tM59NaturalVentilationResults_", NickName = "tM59NaturalVentilationResults_", Description = "Tas.TSDQueryTM59Results.tM59NaturalVentilationResults.", Access = GH_ParamAccess.list, Optional = true }, ParamVisibility.Binding));
                result.Add(new GH_SAMParam(new GooResultParam() { Name = "tM59CorridorResults_", NickName = "tM59CorridorResults_", Description = "Tas.TSDQueryTM59Results.tM59CorridorResults.", Access = GH_ParamAccess.list, Optional = true }, ParamVisibility.Binding));
                result.Add(new GH_SAMParam(new global::Grasshopper.Kernel.Parameters.Param_Boolean() { Name = "tM59Successful_", NickName = "tM59Successful_", Description = "Tas.TSDQueryTM59Results.successful.", Access = GH_ParamAccess.item, Optional = true }, ParamVisibility.Binding));
                result.Add(new GH_SAMParam(new global::Grasshopper.Kernel.Parameters.Param_Boolean() { Name = "workflowSuccessful_", NickName = "workflowSuccessful_", Description = "SAMAnalytical.WorkflowgbXML.successful.", Access = GH_ParamAccess.item, Optional = true }, ParamVisibility.Binding));
                result.Add(new GH_SAMParam(new global::Grasshopper.Kernel.Parameters.Param_String() { Name = "tM52BuildingCategory_", NickName = "tM52BuildingCategory_", Description = "The same wire as Tas.TSDQueryTM59Results._tM52BuildingCategory.", Access = GH_ParamAccess.item, Optional = true }, ParamVisibility.Binding));

                global::Grasshopper.Kernel.Parameters.Param_Boolean boolean = new global::Grasshopper.Kernel.Parameters.Param_Boolean() { Name = "hourly_", NickName = "hourly_", Description = "Also write the hourly companion file. Only produces series where Tas.TSDQueryTM59Results ran with _extended_ = true; every other space's series is written as a refusal record, not silently skipped.", Access = GH_ParamAccess.item, Optional = true };
                boolean.SetPersistentData(false);
                result.Add(new GH_SAMParam(boolean, ParamVisibility.Binding));

                boolean = new global::Grasshopper.Kernel.Parameters.Param_Boolean() { Name = "_run", NickName = "_run", Description = "Connect a boolean toggle to run.", Access = GH_ParamAccess.item };
                boolean.SetPersistentData(false);
                result.Add(new GH_SAMParam(boolean, ParamVisibility.Binding));

                return [.. result];
            }
        }

        /// <summary>
        /// Registers all the output parameters for this component.
        /// </summary>
        protected override GH_SAMParam[] Outputs
        {
            get
            {
                List<GH_SAMParam> result = [];

                result.Add(new GH_SAMParam(new global::Grasshopper.Kernel.Parameters.Param_String() { Name = "path", NickName = "path", Description = "The written summary JSON Lines file path.", Access = GH_ParamAccess.item }, ParamVisibility.Binding));
                result.Add(new GH_SAMParam(new global::Grasshopper.Kernel.Parameters.Param_String() { Name = "pathHourly", NickName = "pathHourly", Description = "The written hourly companion file path, or null where hourly_ was false or nothing extended was available to log.", Access = GH_ParamAccess.item }, ParamVisibility.Binding));
                result.Add(new GH_SAMParam(new global::Grasshopper.Kernel.Parameters.Param_Integer() { Name = "spaceCount", NickName = "spaceCount", Description = "Number of space rows written.", Access = GH_ParamAccess.item }, ParamVisibility.Binding));
                result.Add(new GH_SAMParam(new global::Grasshopper.Kernel.Parameters.Param_Integer() { Name = "scenarioCount", NickName = "scenarioCount", Description = "Number of scenario rows written.", Access = GH_ParamAccess.item }, ParamVisibility.Binding));
                result.Add(new GH_SAMParam(new global::Grasshopper.Kernel.Parameters.Param_Integer() { Name = "unassociatedCount", NickName = "unassociatedCount", Description = "Number of unassociated rows written - a non-zero count is worth investigating.", Access = GH_ParamAccess.item }, ParamVisibility.Binding));
                result.Add(new GH_SAMParam(new global::Grasshopper.Kernel.Parameters.Param_Integer() { Name = "refusalCount", NickName = "refusalCount", Description = "Number of refusal rows written.", Access = GH_ParamAccess.item }, ParamVisibility.Binding));
                result.Add(new GH_SAMParam(new global::Grasshopper.Kernel.Parameters.Param_Boolean() { Name = "successful", NickName = "successful", Description = "True once the intended diagnostic file(s) were written. Refusal rows inside a successfully written log do not themselves make this false.", Access = GH_ParamAccess.item }, ParamVisibility.Binding));

                return [.. result];
            }
        }

        /// <summary>
        /// This is the method that actually does the work.
        /// </summary>
        /// <param name="dataAccess">The DA object is used to retrieve from inputs and store in outputs.</param>
        protected override void SolveInstance(IGH_DataAccess dataAccess)
        {
            int index_Successful = Params.IndexOfOutputParam("successful");
            if (index_Successful != -1)
            {
                dataAccess.SetData(index_Successful, false);
            }

            int index;

            bool run = false;
            index = Params.IndexOfInputParam("_run");
            if (index == -1 || !dataAccess.GetData(index, ref run))
            {
                run = false;
            }

            if (!run)
            {
                return;
            }

            index = Params.IndexOfInputParam("_pathTasTSD");
            string path_TSD = null;
            if (index == -1 || !dataAccess.GetData(index, ref path_TSD) || string.IsNullOrWhiteSpace(path_TSD))
            {
                AddRuntimeMessage(GH_RuntimeMessageLevel.Error, "Invalid data");
                return;
            }

            AnalyticalModel analyticalModel = null;
            index = Params.IndexOfInputParam("_analyticalModel");
            if (index == -1 || !dataAccess.GetData(index, ref analyticalModel) || analyticalModel == null)
            {
                AddRuntimeMessage(GH_RuntimeMessageLevel.Error, "Invalid data");
                return;
            }

            List<Space> spaces = new List<Space>();
            index = Params.IndexOfInputParam("spaces_");
            if (index != -1)
            {
                List<Space> spaces_Temp = new List<Space>();
                if (dataAccess.GetDataList(index, spaces_Temp) && spaces_Temp != null)
                {
                    spaces = spaces_Temp;
                }
            }

            List<OverheatingScenario> overheatingScenarios = new List<OverheatingScenario>();
            index = Params.IndexOfInputParam("overheatingScenarios_");
            if (index != -1)
            {
                List<IAnalyticalObject> analyticalObjects = [];
                if (dataAccess.GetDataList(index, analyticalObjects) && analyticalObjects != null)
                {
                    overheatingScenarios = analyticalObjects.FindAll(x => x is OverheatingScenario).ConvertAll(x => x as OverheatingScenario);
                }
            }

            List<string> notes = ReadStrings(dataAccess, "notes_");
            List<string> refusals = ReadStrings(dataAccess, "refusals_");

            List<TMResult> mechanical = ReadResults(dataAccess, "tM59MechanicalVentilationResults_");
            List<TMResult> natural = ReadResults(dataAccess, "tM59NaturalVentilationResults_");
            List<TMResult> corridor = ReadResults(dataAccess, "tM59CorridorResults_");

            bool? tM59Successful = ReadNullableBool(dataAccess, "tM59Successful_");
            bool? workflowSuccessful = ReadNullableBool(dataAccess, "workflowSuccessful_");

            string tM52BuildingCategory = null;
            index = Params.IndexOfInputParam("tM52BuildingCategory_");
            if (index != -1)
            {
                dataAccess.GetData(index, ref tM52BuildingCategory);
            }

            bool hourly = false;
            index = Params.IndexOfInputParam("hourly_");
            if (index != -1)
            {
                dataAccess.GetData(index, ref hourly);
            }

            PartODiagnosticLogInput input = new PartODiagnosticLogInput
            {
                AnalyticalModel_Design = analyticalModel,
                Spaces_Simulated = spaces,
                OverheatingScenarios = overheatingScenarios,
                Notes = notes,
                Refusals = refusals,
                MechanicalVentilationResults = mechanical,
                NaturalVentilationResults = natural,
                CorridorResults = corridor,
                TM59Successful = tM59Successful,
                WorkflowSuccessful = workflowSuccessful,
                TM52BuildingCategory = tM52BuildingCategory,
                Path_TSD = path_TSD,
            };

            Guid runId = Guid.NewGuid();
            DateTime runTimestampUtc = DateTime.UtcNow;

            PartODiagnosticLogBuildResult result;
            try
            {
                result = PartODiagnosticLog.Build(input, runId, runTimestampUtc, hourly);
            }
            catch (Exception exception)
            {
                //Never throw out of Grasshopper: an unexpected condition here becomes a runtime error and no
                //file is written, rather than a crashed canvas.
                AddRuntimeMessage(GH_RuntimeMessageLevel.Error, "Failed to build the diagnostic log: " + exception.Message);
                return;
            }

            string directory = System.IO.Path.GetDirectoryName(path_TSD);
            string fileName = System.IO.Path.GetFileNameWithoutExtension(path_TSD);
            string iteration = overheatingScenarios.Count != 0 ? overheatingScenarios[0].Iteration.ToString() : "Undefined";
            //Millisecond precision: two runs within the same second for the same TSD and iteration would
            //otherwise compute the same path and the second overwrite the first, losing one run's records.
            string timestamp = runTimestampUtc.ToString("yyyyMMdd-HHmmssfff");

            string path_Log = System.IO.Path.Combine(directory ?? string.Empty, string.Format("{0}.{1}.partO.{2}.jsonl", fileName, iteration, timestamp));

            if (!PartODiagnosticLog.TryWriteJsonLines(result.Records, path_Log, out string error))
            {
                AddRuntimeMessage(GH_RuntimeMessageLevel.Error, "Failed to write the diagnostic log: " + error);
                return;
            }

            string path_LogHourly = null;
            if (hourly && result.HourlyRecords.Count != 0)
            {
                path_LogHourly = System.IO.Path.Combine(directory ?? string.Empty, string.Format("{0}.{1}.partO.{2}.hourly.jsonl", fileName, iteration, timestamp));

                if (!PartODiagnosticLog.TryWriteJsonLines(result.HourlyRecords, path_LogHourly, out string error_Hourly))
                {
                    //The summary file already wrote successfully - a failed hourly companion is reported as a
                    //warning, not a failure of the whole run.
                    AddRuntimeMessage(GH_RuntimeMessageLevel.Warning, "Failed to write the hourly diagnostic log: " + error_Hourly);
                    path_LogHourly = null;
                }
            }

            foreach (JsonObject refusalRecord in result.Records.Where(x => x["record"]?.GetValue<string>() == "refusal"))
            {
                AddRuntimeMessage(GH_RuntimeMessageLevel.Remark, "Diagnostic log refusal: " + refusalRecord["text"]?.GetValue<string>());
            }

            index = Params.IndexOfOutputParam("path");
            if (index != -1)
            {
                dataAccess.SetData(index, path_Log);
            }

            index = Params.IndexOfOutputParam("pathHourly");
            if (index != -1)
            {
                dataAccess.SetData(index, path_LogHourly);
            }

            index = Params.IndexOfOutputParam("spaceCount");
            if (index != -1)
            {
                dataAccess.SetData(index, result.SpaceCount);
            }

            index = Params.IndexOfOutputParam("scenarioCount");
            if (index != -1)
            {
                dataAccess.SetData(index, result.ScenarioCount);
            }

            index = Params.IndexOfOutputParam("unassociatedCount");
            if (index != -1)
            {
                dataAccess.SetData(index, result.UnassociatedCount);
            }

            index = Params.IndexOfOutputParam("refusalCount");
            if (index != -1)
            {
                dataAccess.SetData(index, result.RefusalCount);
            }

            if (index_Successful != -1)
            {
                dataAccess.SetData(index_Successful, true);
            }
        }

        private List<string> ReadStrings(IGH_DataAccess dataAccess, string name)
        {
            List<string> result = new List<string>();

            int index = Params.IndexOfInputParam(name);
            if (index != -1)
            {
                List<string> temp = new List<string>();
                if (dataAccess.GetDataList(index, temp) && temp != null)
                {
                    result = temp;
                }
            }

            return result;
        }

        private List<TMResult> ReadResults(IGH_DataAccess dataAccess, string name)
        {
            List<TMResult> result = new List<TMResult>();

            int index = Params.IndexOfInputParam(name);
            if (index != -1)
            {
                List<IResult> temp = new List<IResult>();
                if (dataAccess.GetDataList(index, temp) && temp != null)
                {
                    result = temp.Where(x => x is TMResult).Select(x => (TMResult)x).ToList();
                }
            }

            return result;
        }

        private bool? ReadNullableBool(IGH_DataAccess dataAccess, string name)
        {
            int index = Params.IndexOfInputParam(name);
            if (index == -1)
            {
                return null;
            }

            bool value = false;
            return dataAccess.GetData(index, ref value) ? value : (bool?)null;
        }
    }
}
